---
title: "00d.SRModels"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(glmmTMB)
library(emmeans)
library(tidyverse)
library(car)
library(dplyr)
library(reshape2)

```

##Test for in SR as predicted by treatment types
```{r}
Srichness <- as.data.frame(cbind("plot" = dat17.split$Plug$plot,  "FD"=dat17.split$Plug$trtD, "PD"=dat17.split$Plug$phyD, "planted"=dat17.split$Plug$SR_planted, "2017"=dat17.split$Plug$SR_observed,  "2018.06" = dat18.05.split$Plug$SR_observed, "2018.09"=dat18.split$Plug$SR_observed, "2019.06"= dat19.06.split$Plug$SR_observed, "2019.09"= dat19.split$Plug$SR_observed))

factor(Srichness$FD, levels = c('L','H')) -> Srichness$FD
factor(Srichness$PD, levels = c('L', 'M', 'H')) -> Srichness$PD

SRdat <- melt(Srichness, id.vars=c("PD", 'FD', "plot"), measure.vars=c('planted','2017', "2018.06", '2018.09', "2019.06", "2019.09"))
names(SRdat) <- c("PD", "FD", "plot", "year", "SR")
SRdat$season <- ifelse(SRdat$year == "2018.06" | SRdat$year == "2019.06", "spring", "summer") 

SRdat$year <- as.numeric(SRdat$year)
SRdat$SR <- as.numeric(SRdat$SR)


#MODELS
#family=gaussian, poisson, nbinom1, truncated_poisson(link = "log")
fitPD <- glmmTMB(SR ~ PD + season + year + (1|plot), data=SRdat, family=gaussian)
summary(fitPD)
Anova(fitPD)
pd.em <- emmeans(fitPD, "PD")
pairs(pd.em)

fitFD <- glmmTMB(SR ~ year + season + FD + (1|plot), data=SRdat, family=gaussian)
summary(fitFD)
Anova(fitFD)
fd.em <- emmeans(fitFD, "PD")
pairs(fd.em)

#interaction:
SRdat <- SRdat %>% 
  unite(PDyear, c("PD", "year"))
fit2PD <- glmmTMB(SR ~ season +  PDyear + (1|plot), data=SRdat, family=gaussian) 
summary(fit2PD)
emmeans(fit2PD, pairwise ~ PDyear)

SRdat <- SRdat %>% 
  unite(FDyear, c("FD", "year"))

fit3PD <- glmmTMB(SR ~ year:FD + (1|plot), data=SRdat, family=gaussian) 
```

##Test for in SR as predicted by raw diversity values
```{r}
df.pa.plug <- df.pa.plug[with(df.pa.plug, order(year, plot)),] # order by year and plot
df.pa.plug$SR <- SRobs

#take dat17.split$Plug$MPD_planted and merge by plot#
df.pa.plug <- merge(df.pa.plug, dat17.split$Plug[, c("plot", "MPD_planted")], by="plot")
df.pa.plug <- merge(df.pa.plug, dat17.split$Plug[, c("plot", "MNTD_planted")], by="plot")
df.pa.plug <- merge(df.pa.plug, dat17.split$Plug[, c("plot", "PD_planted")], by="plot")

```

```{r}
#ADD FDis to model
df.pa.plug <- df.pa.plug %>%
  select(MNTD_planted, MPD_planted, PD_planted, SR, everything())

#df.pa.plug.copy <- df.pa.plug

traits.mat <- read.csv('../DATA/ImputedMiceTraits.2016-01-06.csv', as.is = T, row.names = 1)
rownames(traits.mat)[which(rownames(traits.mat) == "Symphyotrichum_novae-angliae")] <-
  "Symphyotrichum_novae.angliae"
rownames(traits.mat) -> traits.mat$Species

MICEtraits.mat <- traits.mat %>% filter (Species %in% colnames(df.pa.plug[9:ncol(df.pa.plug)]))
MICEtraits.mat$Species -> rownames(MICEtraits.mat)
MICEtraits.mat <- subset(MICEtraits.mat, select = -Species)
dist(MICEtraits.mat) -> dis.trait.diss
as.matrix(df.pa.plug[12:ncol(df.pa.plug)]) -> comm
#Use fdisp measures the functional dispersion (FDis) as in how plots were designed
fdisp(dis.trait.diss, comm, tol = 1e-07) -> FD.df.pa.plug
unlist(FD.df.pa.plug$FDis) -> df.pa.plug$FD
#hill_func(df.pa.plug[,8:length(df.pa.plug)], MICEtraits.mat) #MICE traits

#FD as planted:
planted <- subset(df.pa.plug, year==2016)
FDplanted <- as.data.frame(cbind(planted$plot, planted$FD))
names(FDplanted) <- c("plot", "FDplanted")
new.df.pa.plug <-left_join(df.pa.plug, FDplanted, by="plot")
new.df.pa.plug -> SRdat

#To treat time properly, include a categorical variable for season and then have year be continuous.

SRdat$season <- ifelse(SRdat$year == "2018.06" | SRdat$year == "2019.06", "spring", "summer") 
SRdat$year <- as.numeric(SRdat$year)
#family=gaussian, poisson, nbinom1, truncated_poisson(link = "log")

#NEED TO ADD A PD/FD treatment
fitMPD<- glmmTMB(SR ~ year + season + MPD_planted + (1|plot), data=SRdat, family=gaussian)
summary(fitMPD)
glht(fitMPD, mcp(PD = "Tukey")) 


glmmTMB(SR ~ year + season + MNTD_planted + (1|plot), data=SRdat, family=gaussian)

glmmTMB(SR ~ year + season + PD_planted + (1|plot), data=SRdat, family=gaussian)

glmmTMB(SR ~ year + season + FDplanted + (1|plot), data=SRdat, family=gaussian)

SR.modelFULL <- glmmTMB(SR ~ year + FDplanted + MNTD_planted + MPD_planted + PD_planted + (1|plot), data=new.df.pa.plug, )

Anova(SR.modelFULL)
summary(SR.modelFULL)
#anova(SR.modelFULL)
```



