---
title: "01b.ordi.plots.MICEtraits_CWM"
output: html_document
---

```{r load data}
#Load MICE traits matrix: (species are rownames)
traits.mat <- read.csv('../DATA/ImputedMiceTraits.2016-01-06.csv', as.is = T, row.names = 1)
setDT(traits.mat, keep.rownames = "Species")[]

#Load Cover Data in #00.load.for.analyses
traits.mat <- traits.mat %>% filter (Species %in% colnames(df.cover[8:ncol(df.cover)])) ##Filter to species in cover df and traits matrix:

plots.traits.mat <- df.cover.long2 %>% 
            left_join(traits.mat, by = "Species")

plots.traits.mat$photosyntheticPathway <- as.numeric(sub("C3", "1", plots.traits.mat$photosyntheticPathway))
plots.traits.mat$photosyntheticPathway[is.na(plots.traits.mat$photosyntheticPathway)] <- 0 #replace NA for C4 with 0
drop.traits <- c("floweringStartcoded", "lifeCycleCoded", "wis_IL", "Lifeform", "habitClean")
plots.traits.mat <- plots.traits.mat %>% select (-c(drop.traits))

####Calculate weighted average of traits across species per plot by relative abundance 
weighted.traits.plot <- setDT(plots.traits.mat)[, lapply(.SD, function(x) weighted.mean(x, value, na.rm = TRUE)), by = c("year", "plot", "type", "phyD", "fd"), .SDcols  = seedMass:genome_Use]
weighted.traits.plot -> weighted.traits
```

#Ordination of CWMs  
```{r}
tmds <- metaMDS(weighted.traits.plot[,-c(1:5)], k = 3, maxit = 15000)  
tmds <- metaMDS(weighted.traits.plot[,-c(1:5)], k = 3, maxit = 15000, previous.best = tmds)
#stressplot(tmds) #stress=0.1456962
Wscores <- as.data.frame(scores(tmds)) #extract nmds scores
Wscores <- cbind(year=weighted.traits.plot$year, plot=weighted.traits.plot$plot,phyD=weighted.traits.plot$phyD, fd=weighted.traits.plot$fd, Wscores) #add back in plot, yr, Codes
factor(Wscores$phyD, levels = c('L', 'M', 'H')) -> Wscores$phyD
factor(Wscores$fd, levels = c('L', 'H')) -> Wscores$fd

#SPLIT UP FOR PLOTTING AND MEANS
Wscores2 <- Wscores[,-2]  #take out plot
Wscores4 <- subset(Wscores2, select=-c(fd))


#general plot
MICEplot <- ggplot() + 
  stat_ellipse(data=Wscores4, aes(x=NMDS1,y=NMDS2, color= year)) +
   geom_point(data = Wscores4, aes(NMDS1, NMDS2, color = year),size=3) +
   geom_path(data=centroid, aes(x = NMDS1, y = NMDS2, group = phyD), arrow = arrow(length = unit(0.15, "cm")), colour="black", size = .85) + 
   labs(x="nmds1", y="nmds2", color="year") + theme_bw() 
```

##centroids
```{r}
centroid.Phy <- Wscores4 %>% #removed type and plot 
    group_by(phyD, year) %>% 
    summarise_all(funs(mean))

Wscores3 <- subset(Wscores2, select=-c(phyD))

centroid.fd <- Wscores3 %>% #removed type and plot 
    group_by(fd, year) %>% 
    summarise_all(funs(mean))

```

#add trait vectors:
```{r}
vf <- envfit(tmds, weighted.traits.plot[,-c(1:5)], perm = 9999)
#vec <- as.data.frame(vf.Wtrait$vectors$arrows*sqrt(vf.Wtrait$vectors$r))
scores(vf, "vectors")
spp.scrs <- as.data.frame(scores(vf, display = "vectors"))
spp.scrs <- cbind(spp.scrs, Traits = rownames(spp.scrs))
```

###Plot JUST START TO FINISH:
```{r}
start <- subset(Wscores, year == "2017")
end <- subset(Wscores, year == "2019.09")
dat2 <- rbind(start, end)

dat <-  dat2 %>% 
   arrange(plot) %>%
  arrange(year)


dat %>%  
  ggplot() +
  geom_point(aes(x=NMDS1, y=NMDS2, shape=year, color = fd), size=3) +
  theme_bw() +
  labs(shape="Year", color="FD") +
  #geom_path(aes(x = NMDS1, y = NMDS2, group = plot), arrow = arrow(length = unit(0.15, "cm")), color="grey") +
 geom_segment(data = spp.scrs,
               aes(x = 0, xend = NMDS1/3, y = 0, yend = NMDS2/3),
               arrow = arrow(length = unit(0.25, "cm")), colour = "grey") +
  geom_text_repel(data = spp.scrs, aes(x = NMDS1/3, y = NMDS2/3, label = Traits),
            size = 3) +
  scale_color_manual("FD", values = c("L" = "#332288",
                                "H" = "#44AA99"
                                )) +
   stat_ellipse(data=start, aes(x=NMDS1,y=NMDS2, color= fd)) +
   stat_ellipse(data = end, aes(NMDS1, NMDS2, color = fd)) +
  geom_path(aes(x = NMDS1, y = NMDS2, group = plot), arrow = arrow(length = unit(0.15, "cm")), color="grey")

   #+ geom_path(data=centroid.fd, aes(x = NMDS1, y = NMDS2, group = fd), arrow = arrow(length = unit(0.15, "cm")), colour="red", size = 1)  +

#centroid.Phy.PlugS <- split(centroid.Phy.Plug, centroid.Phy.Plug$phyD)
```

#Plot based on PhyD
```{r}
dat %>%  
  ggplot() +
  geom_point(aes(x=NMDS1, y=NMDS2, shape=year, color = phyD), size=3) +
  theme_bw() +
  labs(shape="Year", color="PD") +
  #geom_path(aes(x = NMDS1, y = NMDS2, group = plot), arrow = arrow(length = unit(0.15, "cm")), color="grey") +
 geom_segment(data = spp.scrs,
               aes(x = 0, xend = NMDS1/3, y = 0, yend = NMDS2/3),
               arrow = arrow(length = unit(0.25, "cm")), colour = "grey") +
  geom_text_repel(data = spp.scrs, aes(x = NMDS1/3, y = NMDS2/3, label = Traits),
            size = 3) +
  scale_color_manual("FD", values = c("L" = "#332288",
                                      "M" = "#117733",
                                "H" = "#44AA99"
                                )) +
   stat_ellipse(data=start, aes(x=NMDS1,y=NMDS2, group = phyD), color= "grey") +
   stat_ellipse(data = end, aes(NMDS1, NMDS2, color = phyD)) 

```