---
title: "PhyloStuff"
output: html_document
---

```{r setup, include=FALSE}
#knitr::opts_chunk$set(echo = TRUE)
library(evobiR)
library(tidyverse)
library(ggtree)
library(ape)
library(phytools)
library(picante)
library(dplyr)
library(data.table)
library(geiger)
library(ggnewscale)
```

#Data
```{r}
###########Loaded from 00.load.for.analyses
head(df.cover) #2017, 2018, 2019 cover
comm <- df.cover
comm[is.na(comm)] <- 0 #convert NAs to 0
#split seed and plug
df.diff.wide.18.split <- split(df.diff.wide.18, df.diff.wide.18$type)
df.diff.wide18.plug <- df.diff.wide.18.split$Plug

df.diff.wide.19.split <- split(df.diff.wide.19, df.diff.wide.19$type)
df.diff.wide19.plug <- df.diff.wide.19.split$Plug

#df.spp.diff <- colMeans(df.diff.wide[,7:length(df.diff.wide)], na.rm = TRUE)
df.spp.diff.plug18 <- colMeans(df.diff.wide18.plug[,8:length(df.diff.wide18.plug)], na.rm = TRUE)
df.spp.diff.plug19 <- colMeans(df.diff.wide19.plug[,8:length(df.diff.wide19.plug)], na.rm = TRUE)

#Mean.ChnageCover <- as.data.frame(cbind(df.spp.diff.plug18, df.spp.diff.seed18))
#Mean.ChnageCover18.09 <- as.data.frame(cbind(df.spp.diff.plug18.09, df.spp.diff.seed18.09))
```
#Phylogeny
```{r}
phy <- read.tree("../DATA/phylogeny.analyzed.2016-01-05b.tre") 
phy$tip.label    #140
#drop tips not in contable
phy$tip.label[which(phy$tip.label == "Symphyotrichum_novae-angliae")] <-
  "Symphyotrichum_novae.angliae"
tree <- drop.tip(phy, which(!phy$tip.label %in% colnames(comm))) 
p <- ggtree(tree)
p + geom_tiplab()
tree2 <- drop.tip(phy, which(!phy$tip.label %in% colnames(df.diff.wide.18[5:ncol(df.diff.wide.18)]))) 
```

###Plot phylogeny with change in cover
```{r}
library(RColorBrewer)
cols <- brewer.pal(3,"YlGnBu")
#ReorderData(tree2, df.spp.diff.plug18) -> Mean.ChnageCover.ordered
#ReorderData(tree2, df.spp.diff.plug19) -> Mean.ChnageCover.ordered19
par(mfrow=c(1,3))
plotTree.barplot(tree2, df.spp.diff.plug18, add=TRUE, args.plotTree=list(fsize=0.45), args.barplot=list(main = "                 Change in Cover", beside=TRUE, legend.text=FALSE, col=cols[2], space=c(0,1.2), border=cols[2], args.legend=list(x=-10,y=65), xlab="2017 - 2018"), args.axis=list(at=seq(-50,50,by=10)))

#add next sampling interval
plotTree.barplot(tree2, df.spp.diff.plug19, args.barplot=list(beside=TRUE, xlab="2018 - 2019",
    col=cols[2], border=cols[2]),args.axis=list(at=seq(-30,30,by=10)), args.plotTree=list(plot=FALSE),add=TRUE)

#adding proporation occupied
        #plotTree.barplot(tree2, plug.prop, args.barplot=list(beside=TRUE, xlab="proportion plots occupied", col=cols[2], border=cols[2]),args.axis=list(at=seq(0,100,by=25)), args.plotTree=list(plot=FALSE),add=TRUE)

```

##PLOT WINNERS/LOSERS TREE WITH CHANGE IN COVER AS HEAT MAP
```{r}
#cbind the proportion of plots occupied, chnage in cover df, reorder per phylogeny
CovChange2 <- cbind(df.spp.diff.plug18, df.spp.diff.plug19)
as.data.frame(CovChange2) -> CovChange2
ReorderData(tree, CovChange2, taxa.names = "row names") -> CovChange
poor.establishers <- c('Castilleja_coccinea',
                            'Asclepias_hirtella',
                            'Asclepias_syriaca',
                            'Dalea_purpurea',
                            "Helianthus_strumosus",
                            'Juncus_interior',
                            'Juncus_tenuis',
                            'Verbena_stricta',
                            'Asclepias_sullivantii',
                            'Baptisia_bracteata',
                            'Ceanothus_americanus',
                            'Dalea_candida',
                            'Senna_hebecarpa',
                            'Hypericum_punctatum',
                            'Lilium_michiganense',
                            'Symphyotrichum_sericeum')
fig5.tree <- ggtree(tree) + geom_tiplab(size=1.5, offset=0.5) 
  # geom_hilight(node=192, fill="steelblue", alpha=0.2, extend=0) + 
 ##geom_hilight(node=233, fill="darkgreen", alpha=0.2, extend=0) + #Lamiaceae
 #geom_hilight(node=173, fill="pink", alpha=0.2, extend=0) + #Fabaceae
 #geom_hilight(node=169, fill="pink", alpha=0.2, extend=0) + #Rosaceae
 #geom_hilight(node=147, fill="pink", alpha=0.2, extend=0) #Poaceae

names(CovChange) <- c("yr1-yr2", "yr2-yr3")
legend_title1 <- "cover change"
p11 <- gheatmap(fig5.tree, data.frame(CovChange), offset=55, width=0.15, colnames = TRUE, colnames_position = "top",  colnames_angle = 45, hjust=0, colnames_offset_y=1,colnames_offset_x=1, font.size=2.5, low = "steelblue3", high = "red3") +
scale_fill_gradient2(low = "steelblue3", mid = "white",  high = "red3", midpoint = 0, legend_title1) 

####ADD proportion of plots occupied (code below) to figure
fig5 <- p11 + new_scale_fill()
legend_title2 <- c("plots occupied")
fig5.2 <- gheatmap(fig5, as.data.frame(propr), offset=87, width=0.06,
                colnames = TRUE, colnames_position = "top",  colnames_angle = 45, font.size = 3.5, low="white", high="black") +
  scale_fill_gradient2(low = "white", mid="grey99", high = "grey28", legend_title2) + #green
  theme(legend.position="right", legend.title=element_text() ) 

fig5.2
#ggsave(file="../OUT/Fig5.winner_loser_phylo.pdf")

#Reorder to match phylogeny
#contbale from winners.losers and contable.ordered.s
ReorderData(tree, contable.19, taxa.names=1) -> contable.ordered
#as.data.frame(contable.combo) -> CC
as.data.frame(contable.ordered) -> CC
CC$species -> rownames(CC)
plug.prop <- subset(CC, select=c(species,test_stat_plug))
#seed.prop <- subset(CC, select=test_stat_seed)
propr <- as.data.frame(CC$test_stat_plug)
CC$species -> rownames(propr)
names(propr) <- "prop"
```


#Test for Phylogenetic Signal of proportion and change in cover
```{r}
#pagel's Lamba and B's k:
prop.sig <- phylosig(tree2, CC$test_stat_plug, method="lambda", test=TRUE)
prop.sigK <- phylosig(tree2, contable.ordered$test_stat_plug, method="K", test=TRUE)
prop.sig$lambda
prop.sigK$K

ReorderData(tree2, df.spp.diff.plug19) -> df.spp.diff.plug19
change.sig <- phylosig(tree2, df.spp.diff.plug19, method="lambda", test=TRUE)
change.sigK <- phylosig(tree2, df.spp.diff.plug19, method="K", test=TRUE)
change.sig$lambda
change.sigK$K

#df.spp.diff.plug18
#df.spp.diff.plug19
ReorderData(tree2, df.spp.diff.plug18, taxa.names=1) -> Change18.ordered
ReorderData(tree, df.spp.diff.plug19, taxa.names=1) -> Change19.ordered
as.data.frame(Change18.ordered) -> C

Ch.sig <- phylosig(tree2, C$Change18.ordered, method="lambda", test=TRUE)
Ch.sigK <- phylosig(tree2, C$Change18.ordered, method="K", test=TRUE)
tree.di <- multi2di(tree2)

#---- runs models
lambdaModel <- fitContinuous(tree.di, C, model = "lambda")
brownianModel <- fitContinuous(tree.di, C)
OUModel <- fitContinuous(tree.di, C, model = "OU") #errors
EBModel <- fitContinuous(tree.di, C, model = "EB")

# calculate AIC weights
bmAICC <- brownianModel$opt$aicc
#ouAICC <- OUModel$opt$aicc
ebAICC <- EBModel$opt$aicc
aicc <- c(bmAICC, ebAICC)
aiccD <- aicc - min(aicc)
aw <- exp(-0.5 * aiccD)
aiccW <- aw/sum(aw)
aiccW
```

#Plot the same using ggplot
```{r}
dat3 <- facet_plot(fig5.tree, panel='2017 - 2018', data= as.data.frame(CovChange), geom=geom_segment, 
           aes(x=0, xend=value, y=y, yend=y), size=3, color=cols[2])
dat4 <- data.frame(id=tree2$tip.label, value=df.spp.diff.plug19)
dat5 <- facet_plot(dat3, panel='mean change 2018 - 2019', data=dat4, geom=geom_segment, 
           aes(x=0, xend=value, y=y, yend=y), size=3, color=cols[2])
dat5
```

#PLOTTING TRAIT Values ON PHYLOGENY
```{r}
MICEtraits <- read.csv('../DATA/ImputedMiceTraits.2016-01-06.csv', row.names = 1)
setDT(MICEtraits, keep.rownames = "Species")[]
#drop traits:
MICEtraits.drp <- subset(MICEtraits, select = -c(lifeCycleCoded, floweringStartcoded, wis_IL) )
MICEtraits.drp$Species <- gsub("Symphyotrichum_novae-angliae", "Symphyotrichum_novae.angliae" , MICEtraits.drp$Species)
##Filter to only species in 2017 and 2018 cover (drop spring and misc - total 105 species vs as.planted has 127 species
MICEtraits.drp <- MICEtraits.drp %>% filter (Species %in% colnames(df.cover[5:length(df.cover)]))
MICEtraits.drp$Species -> rownames(MICEtraits.drp)
#MICEtraits.drp <- MICEtraits.drp[,-1]

#Load species translate table - species names with codes
spp.trans <- read.delim('../DATA/sp.trans.tsv.txt') #, as.is = T)
spp.trans <- spp.trans[!(spp.trans$CODE == ""), ]
#TRAITS MATRIX:
traits.full <- read.delim('../DATA/prairie.spp.list.v11.2016-01-05.tsv') #, as.is = T, row.names = 1)
#See 01a.ordi.plots.MICEtraits.Rmd for MICE traits
#select.traits <- subset(traits.full, select=c(seedMass, LDMC, SLA, LNC, LCC, LPC, SDMC, flowerHeight,vegetativeHeight, photosyntheticPathway, leafLength, leafThickness, leafWidth, petioleLength, genome_Use))
#select these traits to be consistent with traits.mat
select.traits <- subset(traits.full, select=c(seedMass, LDMC, SLA, LNC, LCC, LPC, SDMC,circularity, flowerHeight,vegetativeHeight, leafLength, leafThickness, leafWidth, petioleLength, photosyntheticPathway, genome_Use, nFixer, adventitious, primary, bulbs, corms, fibrous, rhizomes, stolons, tubers))

#convert photosynthetic pathway:
select.traits$photosyntheticPathway <- as.numeric(sub("C3", "1", select.traits$photosyntheticPathway))
select.traits$photosyntheticPathway <- as.numeric(sub("C4", "0", select.traits$photosyntheticPathway))
# the first col in test.traits isn't named because they are row names. add it:
setDT(select.traits, keep.rownames = "Species")[]
head(select.traits)
head(spp.trans) #species translate table. traits matrix in spp.trans$Scientific.Name and plots in 
#replace test.traits$Species with spp translate table: match spp.trans$Scientific.Name & replace with spp.trans$treeName
indexSp <- match(select.traits$Species, spp.trans$Scientific.Name, nomatch = 0 )
select.traits$Species[indexSp != 0] <- spp.trans$treeName[indexSp]
##Filter to only species in 2017 and 2018 cover (drop spring and misc)
traits107 <- select.traits %>% filter (Species %in% colnames(df.cover[5:ncol(df.cover)]))
head(traits107)
#load phylogeny
phylo <- read.tree("../DATA/phylogeny.analyzed.2016-01-05b.tre")
plot(phylo) #140 tips
#matrix of abundance data.  
samp <- df.cover[5:ncol(df.cover)] #2017 and 2018 seed and plug
##CONVERT NAs to 0:
samp[is.na(samp)] <- 0
#matrix with discrete character data renamed 'traits'
five.traits.df <- subset(MICEtraits.drp, select = c(seedMass,LDMC, SLA, LNC, vegetativeHeight))
#prune any taxa from our tree that are not also represented in our sample matrix
prunedphy <- prune.sample(samp = samp, phylo)
#make sure the species are arranged in the some order in the community data and the phylogeny
samporder <- samp[, prunedphy$tip.label]
samporder 
#visualize the trait data that we have. We'll plot the traits with a different color for each trait value:
par(mfrow = c(2, 2))

for (i in names(five.traits.df)) {
  plot(phylo, show.tip.label = FALSE, main = i)
  tiplabels(pch = 22, col = five.traits.df[, i] + 1, bg = five.traits.df[,i] + 1, cex = 1.5)
}
#svl <- as.matrix(five.traits.df)[, 5]
#obj <- contMap(phylo, svl, fsize = c(0.6, 1), outline = FALSE)

ggplot()
plot(phylo, show.tip.label = FALSE, main = names(five.traits.df)[1])
  tiplabels(pch = 22, col = five.traits.df[, 1], bg = five.traits.df[,1], cex = 1.5)
  ggtree(phylo)
  
```
#Extra figures
```{r}
phylo$tip.label[which(phylo$tip.label == "Symphyotrichum_novae-angliae")] <-
  "Symphyotrichum_novae.angliae"
tree <- drop.tip(phylo, which(!phylo$tip.label %in% rownames(five.traits.df))) 
as.matrix(t.new) -> m.t.new
rownames(m.t.new) <-m.t.new[,1] 
subset(m.t.new, select=-label) -> m.t.new

dotTree(tree, five.traits.df[1:5], labels=TRUE, legend=TRUE, standardize=TRUE, data.type="continuous", fsize=0.5)
#Try with ggtree, traits as heatmap
p8 <- ggtree(tree) +
  xlim(0, 300) +
  geom_tiplab(size=2, offset=1) 
#
five.traits.dfCOPY <- five.traits.df
lf <-log(five.traits.dfCOPY$seedMass)
lf.2 <- (lf - min(lf))
lf.2 <- lf.2 / max(lf.2)


#five.traits.dfCOPYlog<- apply(five.traits.df, 1:2, log) #first log
ft.rescale <- apply(five.traits.dfCOPY, 2, function(x) { #then scale
  x2 = log(x)
  x2 <- x2 - min(x2)
  x2 <- x2 / max(x2)
  x2
})
min(five.traits.dfCOPY$vegetativeHeight) - five.traits.dfCOPY$vegetativeHeight -> five.traits.dfCOPY$vegetativeHeightnew

log(five.traits.dfCOPY[1:8]) -> five.traits.dfCOPY.logged
# add heatmap/traits
p9 <-  gheatmap(p8, ft.rescale, offset=50, width=0.2, low="white", high="black", colnames_position = "top", font.size=2)
plot(p9)

###GGTREE:::
as_tibble(rownames_to_column(five.traits.df)) -> five.traits
five.traits <- five.traits %>% rename(label = rowname) 
t.new <- five.traits
t.new[, 2:6] <- log(t.new[,2:6], 2) #log transform traits
library(tidytree)
x <- as_tibble(tree)
tree22 <- full_join(x, five.traits, by = 'label') %>% as.treedata

#full_join(x, d, by = 'node') %>% as.treedata
tree3 <- full_join(x, t.new[,1:2], by = 'label') %>% as.treedata

ggtree(tree3, aes(color=seedMass)) + geom_tiplab(size=2) + theme(legend.position = c(.05, .85)) + xlim(0, 300) + labs(title="log Seed Mass")

ggtree(tree22, aes(color=seedMass)) + geom_tiplab(size=2) + theme(legend.position = c(.05, .85)) + xlim(0, 300) + labs(title="Seed Mass")

ggtree(tree22, aes(color=vegetativeHeight)) + geom_tiplab(size=2) + theme(legend.position = c(.05, .85)) + xlim(0, 300) + labs(title="vegetative Height")

ggtree(tree22, aes(color=LDMC)) + geom_tiplab(size=2) + theme(legend.position = c(.05, .85)) + xlim(0, 300) + labs(title="LDMC")

ggtree(tree22, aes(color=SLA)) + geom_tiplab(size=2) + theme(legend.position = c(.05, .85)) + xlim(0, 300) + labs(title="SLA")

ggtree(tree22, aes(color=LNC)) + geom_tiplab(size=2) + theme(legend.position = c(.05, .85)) + xlim(0, 300) + labs(title="LNC")
```