---
title: "00.load.and.format.cover.Rmd"
output: html_document
---
```{r setup, include=FALSE}
#knitr::opts_chunk$set(echo = TRUE)
library(data.table)
library(ape)
library(picante)
library(tidyverse)
library(zoo)
library(dplyr)
library(tidyr)

```

##Load Data Cover Data
Notes:
1)2017 data uses a different script - 00.load.and.format.2017cover.R 
2)Plug plots (with monocultures) and seed plots are loaded as seperate csv files for 2018-2019 data. 
3)Formatting for Plug and Monocultures are in different code blocks
```{r}
#LOAD RAW SURVEY DATA - PLUGS
orig_name <- ("../DATA/2019_VegetationCover/VegetationCover.2019.09.Plug.csv") 
dat <- read.csv(orig_name, sep=",", as.is = TRUE)
dat.headers <- c("plot", "type", "sp", "cc.total", "cc01", "cc02", "cc03", "cc04",
                "cc05", "cc06", "cc07", "cc08", "cc09", "cc10", "cc11", "cc12",
                "cc13", "cc14", "cc15", "collector", "date", "notes")
names(dat) <- dat.headers
na.locf(dat$plot) -> dat$plot #fill down plot number into rows:
dat[which(dat$type == ''), 'type'] <- 'Plug' #insert "plug" into blank type column fields:
dat <- dat[,1:19] #drop the "collector", "date", "notes" columns
head(dat) #Mono and Plugs data. Seeds on seperate sheet
#select only plug plots, removing vouchers and monoculture plots, move onto monoculture code below as needed
dat.plug <- subset(dat, type=="Plug" | type=="cov", select=plot:cc15)
dat.plug <- dat.plug[!grepl("CONTROL", dat.plug$sp),] #remove CONTROL rows in sp column
dat.plug2 <- dat.plug %>% 
  mutate_at(vars(matches("sp|cc.total")), lead) %>% #per row, copy direction and total from the following row
  mutate_at(vars(matches("cc\\d+$")),    #create new columns for obs data, fill in values from following row
            .funs = funs(n = lead(.))) 

datp.split  <- split(dat.plug2, dat.plug2$sp) 
datplug.sw <- datp.split$SW
datplug.nw <- datp.split$NW
datplug.se <- datp.split$SE

##########SAVE RAW MATRIX FOR PD METRICS:
file_name <- basename(orig_name)
gsub(".csv", "", file_name) -> file_name #dtop the .csv
gsub("^.*?\\.","", file_name) -> file_name
gsub("\\..*","", file_name) -> year
sub("^([^.]*.[^.]*).*", "\\1", file_name) -> date
datplug.sw$year <- date
matrix_name <- paste0("RAW.sppCovMat.",file_name)
#outname <- paste(file_name, format(Sys.time(), c('%Y-%m-%d')), 'csv', sep = '.')
write.csv(datplug.sw, file=paste0("../DATA/",year,"_VegetationCover/", matrix_name, ".csv"))

sppTemp.sw <- unique(unlist(datplug.sw[5:19])) #sppTemp.sw <- unique(unlist(df18.SW[20:34])) #species codes
sppMatTemp.sw <- matrix(NA, dim(datplug.sw)[1], 127, dimnames = list(paste(datplug.sw$plot, datplug.sw$sp), sppTemp.sw)) #create empty matrix- species codes- 127 col as spp x plots:
#replace NA with cover values: Only 15 sp per row should populate:
for(i in 1:dim(sppMatTemp.sw)[1]) { 
  sppMatTemp.sw[i, as.character(datplug.sw[i, 5:19])] <- as.numeric(datplug.sw[i, 20:34]) 
}

spp.trans <- read.delim('../DATA/sp.trans.tsv.txt')
mm <- match(colnames(sppMatTemp.sw), spp.trans$CODE) #match spp.trans$CODE with col names in df. replace with corresponding spp.trans$treeName:
colnames(sppMatTemp.sw)[!is.na(mm)] <- as.character(spp.trans$treeName[na.omit(mm)])
sppMatTemp.sw <- sppMatTemp.sw[, order(colnames(sppMatTemp.sw))] #order the columns
gsub(" SW", "", rownames(sppMatTemp.sw)) -> rownames(sppMatTemp.sw) #remove the sw from rownames
as.data.frame(sppMatTemp.sw) -> sppMatTemp.sw
names(sppMatTemp.sw)[which(names(sppMatTemp.sw) == "Symphyotrichum_novae-angliae")] <-
  "Symphyotrichum_novae.angliae"

covKey <- read.delim('../DATA/VegetationCover.v2.key.tsv', as.is = T, row.names = 1) #replace values with covKey:
covKey$mid <- apply(covKey[, c('low', 'high')], 1, mean) #apply mean cover interval ( 0-1% is 0.5)
covKey$class.2018[15] <- 14 #add a 14 interval

sppCov.sw <- sppMatTemp.sw
sppCov.sw[] <- lapply(sppMatTemp.sw, function(x) covKey$mid[match(x, covKey$class.2018)]) #loop over columns, match values in lookup table. store in "new".
rownames(sppCov.sw) -> sppCov.sw$plot 

file_name <- basename(orig_name)
gsub(".csv", "", file_name) -> file_name #dtop the .csv
gsub("^.*?\\.","", file_name) -> file_name
#get the year to add to a new column:
gsub("\\..*","", file_name) -> year
sub("^([^.]*.[^.]*).*", "\\1", file_name) -> date
sppCov.sw$year <- date

###Here or move to load.and.format for analyses:
code <- read.csv(file ="../DATA/plot.PD.codes.csv", as.is = TRUE, sep=",")
merge(sppCov.sw, code[, c("plot", "Code", "type")], by="plot") -> sppCov.sw2
sppCov.sw2[order(as.numeric(sppCov.sw2$plot)),] -> sppCov.sw2 #reorder by plot#
sppCov.sw2 <- sppCov.sw2 %>% #Reorder columns for plot is first and year is second:
    select(Code, everything()) %>%
    select(year, everything()) %>%
    select(type, everything()) %>%
    select(plot, everything()) 
new_name <- paste0("COVER.sppCovMat.",file_name)
#outname <- paste(file_name, format(Sys.time(), c('%Y-%m-%d')), 'csv', sep = '.')
write.csv(sppCov.sw2, file=paste0("../DATA/",year,"_VegetationCover/", new_name, ".csv"))
```

#Mean cover values for NW, SW, SE corners
```{r}
Qcover <- rbind(datplug.se, datplug.sw, datplug.nw)
Qcover <- Qcover %>% 
  mutate_at(vars(cc01_n:cc15_n), as.numeric) #convert to numeric
Qcov <- Qcover 
#convert cover to get mean then make df
Qcov[,20:34] <- lapply(Qcover[,20:34], function(x) covKey$mid[match(x, covKey$class.2018)]) #convert coverClass with covKey
Q.means<- Qcov
Q.means<- aggregate(Qcov[,20:34], list(Qcov$plot), mean) #group by plot and take mean
QcovM <- merge(Qcov[1:72,1:19], Q.means, by.x = "plot", by.y = "Group.1" )
#drop sp & cc.total
sppTemp <- unique(unlist(QcovM[5:19])) #sppTemp.sw <- unique(unlist(df18.SW[20:34])) #species codes
sppMatTemp <- matrix(NA, dim(QcovM)[1], 127, dimnames = list(paste(QcovM$plot), sppTemp)) #create empty matrix- species codes- 127 col as spp x plots:
#replace NA with cover values: Only 15 sp per row should populate:
for(i in 1:dim(sppMatTemp)[1]) { 
  sppMatTemp[i, as.character(QcovM[i, 5:19])] <- as.numeric(QcovM[i, 20:34]) 
}
spp.trans <- read.delim('../DATA/sp.trans.tsv.txt')
mm <- match(colnames(sppMatTemp), spp.trans$CODE) #match spp.trans$CODE with col names in df. replace with corresponding spp.trans$treeName:
colnames(sppMatTemp)[!is.na(mm)] <- as.character(spp.trans$treeName[na.omit(mm)])
#sppMatTemp <- sppMatTemp[, order(colnames(sppMatTemp))] 
sppMatTemp <- as.data.frame(sppMatTemp)
rownames(sppMatTemp) -> sppMatTemp$plot 
#save as sppCovMat.Means.#surveydate

file_name <- basename(orig_name)
gsub(".csv", "", file_name) -> file_name #dtop the .csv
gsub("^.*?\\.","", file_name) -> file_name
#get the year to add to a new column:
gsub("\\..*","", file_name) -> year
sub("^([^.]*.[^.]*).*", "\\1", file_name) -> date
sppMatTemp$year <- date

new_name <- paste0("Means.sppCovMat.",file_name)
#outname <- paste(file_name, format(Sys.time(), c('%Y-%m-%d')), 'csv', sep = '.')
write.csv(sppMatTemp, file=paste0("../DATA/",year,"_VegetationCover/", new_name, ".csv"))
```

#Monocultures
```{r}
#if orig_name = final survey run this:
head(dat)
dat.mono <- subset(dat, type=="Mono", select=plot:cc02) #select Monoculture only:
gsub("SW", "", dat.mono$cc01) -> dat.mono$cover #remove the sw from cc01
dat.mono.sw <- subset(dat.mono, select=-c(cc.total, cc01, cc02)) #extract SW quarter as in treatment plots
dat.mono.cov <- dat.mono.sw #copy
dat.mono.cov$cover <- as.numeric(dat.mono.cov$cover)
dat.mono.cov$cover.new <- lapply(dat.mono.cov$cover, function(x) covKey$mid[match(x, covKey$class.2018)]) #convert cover, loop over columns, match to lookup table. store in "new".

dat.mono.cov$cover.new  <-unlist(dat.mono.cov$cover.new) #need this to save as csv- dont know why
monomatch <- match(dat.mono.cov$sp, spp.trans$CODE)
dat.mono.cov$sp[!is.na(monomatch)] <- as.character(spp.trans$treeName[na.omit(monomatch)]) #replace sp with full species_names for later matching

#Mono_outname <- paste(mono_name, format(Sys.time(), c('%Y-%m-%d')), 'csv', sep = '.')
file_name <- basename(orig_name)
gsub(".csv", "", file_name) -> file_name #dtop the .csv
gsub("^.*?\\.","", file_name) -> file_name
#get the year to add to a new column:
gsub("\\..*","", file_name) -> year
sub("^([^.]*.[^.]*).*", "\\1", file_name) -> date
dat.mono.cov$year <- date

mono_name <- paste0("Mono.", file_name)
#outname <- paste(file_name, format(Sys.time(), c('%Y-%m-%d')), 'csv', sep = '.')
write.csv(dat.mono.cov, file=paste0("../DATA/",year,"_VegetationCover/", mono_name, ".csv"))
```

#Format Seed Plots
SW quarter only
```{r}
############FORMAT SEED PLOTS###############
orig_name <- ("../DATA/2019_VegetationCover/VegetationCover.2019.06.Seed.csv") 
dat.seed <- read.csv(orig_name, sep=",", as.is = TRUE)
names(dat.seed) <- dat.headers 
na.locf(dat.seed$plot) -> dat.seed$plot #fill down plot number into rows:
dat.seed[which(dat.seed$type == ''), 'type'] <- 'cov' #insert "cov" into blank type column fields:
dat.seed <- dat.seed[,1:19] #drop "collector", "date", "notes" columns 
dat.seed.sw <- dat.seed[!grepl("NW", dat.seed$sp),] #extract only the SW; remove all rows with NW
##Remove rows with CONTROL in sp col (control plots) AND any rows that have plot# matching that of CONTROL:
#dat18seed.sw <- dat18seed.sw[!grepl("CONTROL", dat18seed.sw$sp),]
datseed <- subset(dat.seed.sw, !plot %in% plot[sp == 'CONTROL'] & sp != "CONTROL")

datseed2 <- datseed %>% 
  mutate_at(vars(matches("sp|cc.total")), lead) %>%  #for each row, copy the direction and total from the following row
  mutate_at(vars(matches("cc\\d+$")), #create new columns for obs data, fill in values from following row
            .funs = funs(n = lead(.)))

datseed2 <- split(datseed2, datseed2$sp) 
datseed.sw <- datseed2$SW
#NEED TO REPLACE x and * WITH 0:
datseed.sw2 = reshape2::dcast(
   dplyr::mutate(
      reshape2::melt(datseed.sw, id.var="plot"),
      value=plyr::mapvalues(
           value, c("x","*", "X"),c("0","0", "0"))
   ), plot~variable)
###WONKY Characters in spreadsheet:  need to add "0" where there are blanks and delete the "F"
datseed.sw3 <- data.frame(lapply(datseed.sw2, function(x) {
                  gsub(" F", "", x)
              }))

datseed.sw3[20:34] <- data.frame(lapply(datseed.sw3[20:34], function(x) {
                  gsub("F", "", x)
              }))
NNN <- as.data.frame(apply(datseed.sw3, 2, function(x) gsub("^$|^ $", 0, x))) #replace empty cells:
NNN[20:34] <- lapply(NNN[20:34], function(x) as.numeric(gsub("[*]", "", x)) ) # remove *
NNN -> datseed.sw4
##########SAVE RAW MATRIX FOR PD METRICS:
file_name <- basename(orig_name)
gsub(".csv", "", file_name) -> file_name #dtop the .csv
gsub("^.*?\\.","", file_name) -> file_name
gsub("\\..*","", file_name) -> year
sub("^([^.]*.[^.]*).*", "\\1", file_name) -> date
datseed.sw4$year <- date
matrix_name <- paste0("RAW.sppCovMat.",file_name)
#outname <- paste(file_name, format(Sys.time(), c('%Y-%m-%d')), 'csv', sep = '.')
write.csv(datseed.sw4, file=paste0("../DATA/",year,"_VegetationCover/", matrix_name, ".csv"))
  #covKey <- read.delim('../DATA/VegetationCover.v2.key.tsv', as.is = T, row.names = 1) #replace values with covKey:
  #covKey$mid <- apply(covKey[, c('low', 'high')], 1, mean) #apply mean for cover interval (i.e. coverage block 0-1% is 0.5)
  #covKey$class.2018[15] <- 14 #add a 14 interval
  #dat.seed <- datseed.sw4  # create a copy of df
  #dat.seed[,20:34] <- lapply(datseed.sw2[,20:34], function(x) covKey$mid[match(x, covKey$class.2018)]) # using lapply, loop over columns, match values look up table. store in "new".
  #Do the same for cc.total col:
  #dat.seed2 <- dat.seed
  #dat.seed2[,4] <- sapply(dat.seed[,4], function(x) covKey$mid[match(x, covKey$class.2018)]) #dat.seed2 is used for the PD metrics below

datseed.sw4 -> dat.seed2
sppTemp <- unique(unlist(dat.seed2[5:19])) #extract species codes
sppMatTemp.sw <- matrix(NA, dim(dat.seed2)[1], 127, dimnames = list(paste(dat.seed2$plot, dat.seed2$sp), sppTemp)) #CREATE EMPTY MATRIX with the species codes- 127 col as spp x plots:

for(i in 1:dim(sppMatTemp.sw)[1]) {  #replace NA with cover values: Only 15 sp per row should populate.
  sppMatTemp.sw[i, as.character(datseed.sw2[i, 5:19])] <- as.numeric(datseed.sw2[i, 20:34])
}

spp.trans <- read.delim('../DATA/sp.trans.tsv.txt') #match spp.trans$CODE with col names in df. replace with corresponding spp.trans$treeName:
mm <- match(colnames(sppMatTemp.sw), spp.trans$CODE)
colnames(sppMatTemp.sw)[!is.na(mm)] <- as.character(spp.trans$treeName[na.omit(mm)])
sppMatTemp.sw <- sppMatTemp.sw[, order(colnames(sppMatTemp.sw))] #order the columns
gsub(" SW", "", rownames(sppMatTemp.sw)) -> rownames(sppMatTemp.sw) #remove the sw from rownames
as.data.frame(sppMatTemp.sw) -> sppMatTemp.sw
names(sppMatTemp.sw)[which(names(sppMatTemp.sw) == "Symphyotrichum_novae-angliae")] <-
  "Symphyotrichum_novae.angliae"

covKey <- read.delim('../DATA/VegetationCover.v2.key.tsv', as.is = T, row.names = 1) #replace values with covKey:
covKey$mid <- apply(covKey[, c('low', 'high')], 1, mean) #apply mean for cover interval (i.e. coverage block 0-1% is 0.5)
covKey$class.2018[15] <- 14 #add a 14 interval

sppCov.sw <- sppMatTemp.sw  # create a copy of df
sppCov.sw[] <- lapply(sppMatTemp.sw, function(x) covKey$mid[match(x, covKey$class.2018)]) #loop over columns, match values to look up table. store in "new".
sppCov.sw$plot <- rownames(sppCov.sw) #puts plot at end

file_name <- basename(orig_name)
gsub(".csv", "", file_name) -> file_name #dtop the .csv
gsub("^.*?\\.","", file_name) -> file_name
gsub("\\..*","", file_name) -> year
sub("^([^.]*.[^.]*).*", "\\1", file_name) -> date
sppCov.sw$year <- date

code <- read.csv(file ="../DATA/plot.PD.codes.csv", as.is = TRUE, sep=",")
merge(sppCov.sw, code[, c("plot", "Code", "type")], by="plot") -> sppCov.sw2
sppCov.sw2[order(as.numeric(sppCov.sw2$plot)),] -> sppCov.sw2 #reorder by plot#
sppCov.sw2 <- sppCov.sw2 %>% #Reorder columns for plot is first and year is second:
    select(Code, everything()) %>%
    select(year, everything()) %>%
    select(type, everything()) %>%
    select(plot, everything()) 

new_name <- paste0("COVER.sppCovMat.",file_name)
#outname <- paste(file_name, format(Sys.time(), c('%Y-%m-%d')), 'csv', sep = '.')
write.csv(sppCov.sw2, file=paste0("../DATA/",year,"_VegetationCover/", new_name, ".csv"))
```

#Take mean cover values for seed plots NW/SW
```{r}
############FORMAT SEED PLOTS###############
#dat.headers and covKey loaded above
orig_name <- ("../DATA/2019_VegetationCover/VegetationCover.2019.06.Seed.csv") 
dat.seed <- read.csv(orig_name, sep=",", as.is = TRUE)

names(dat.seed) <- dat.headers 
na.locf(dat.seed$plot) -> dat.seed$plot #fill down plot number into rows:
dat.seed[which(dat.seed$type == ''), 'type'] <- 'cov' #insert "cov" into blank type column fields:
dat.seed <- dat.seed[,1:19] #drop "collector", "date", "notes" columns 
dat.seed.sw <- dat.seed[!grepl("NW", dat.seed$sp),] #extract only the SW; remove all rows with NW
dat.seed.nw <- dat.seed[!grepl("SW", dat.seed$sp),] #extract only the NW; remove all rows with SW

#loop through below to get a wide df for dat.seed.* then take mean later
#coverQuarter = list(nw = dat.seed.nw, sw = dat.seed.sw)
#for (Q in names(coverQuarter)){
#  datTemp <- coverQuarter[[Q]]
#datTemp <- dat.seed.sw
Qseed <- rbind(dat.seed.sw, dat.seed.nw)
datTemp <- Qseed
#datTemp <- dat.seed.sw
    
ds <- subset(datTemp, !plot %in% plot[sp == 'CONTROL'] & sp != "CONTROL") #drop Control plots
ds <- ds %>% 
    mutate_at(vars(matches("sp|cc.total")), lead) %>%  
    mutate_at(vars(matches("cc\\d+$")), #fill in values from following row
              .funs = funs(n = lead(.)))

ds2 <- ds %>%
filter(sp == "SW" | sp == "NW") 

    #NEED TO REPLACE X "and "" WITH 0:
datS <- as.data.frame(apply(ds2, 2, function(x) gsub("^$|^ $", 0, x))) #replace empty cells:
datS[datS == "X"] <- 0
datS -> datScopy
datScopy[,20:34] <- lapply(datScopy[,20:34], function(x) covKey$mid[match(x, covKey$class.2018)]) #convert cover 
#group_by plot and take mean value
Dmeans <- datScopy %>%
  group_by(plot) %>%
  #dplyr::select_if(datScopy, is.numeric) %>%
  summarise_all(funs(if(is.numeric(.)) mean(., na.rm = TRUE))) # else paste(., collapse="")))
  
#do an if numeric
Max <- merge(ds2copy2[1:72, 1:19], means, by="plot")
Max2 <-  subset(Max, select = -c(type, sp, cc.total))

maxTemp <- unique(unlist((Max2[2:16]))) #extract species codes
maxTemp <- as.character(maxTemp)
maxMatTemp <- matrix(NA, dim(Max2)[1], 127, dimnames = list(paste(Max2$plot), maxTemp)) #CREATE EMPTY MATRIX with the species codes- 127 col as spp x plots:

######HELP ??????????
for(i in 1:dim(maxMatTemp)[1]) {  #replace NA with cover values: Only 15 sp per row should populate.
  maxMatTemp[i, as.character(Max2[i, 2:16])] <- as.numeric(Max2[i, 17:31])
}

spp.trans <- read.delim('../DATA/sp.trans.tsv.txt') #match spp.trans$CODE with col names in df. replace with corresponding spp.trans$treeName:
mm <- match(colnames(sppMatTemp.sw), spp.trans$CODE)
colnames(sppMatTemp.sw)[!is.na(mm)] <- as.character(spp.trans$treeName[na.omit(mm)])
sppMatTemp.sw <- sppMatTemp.sw[, order(colnames(sppMatTemp.sw))] #order the columns
#gsub(" NW", "", rownames(sppMatTemp.sw)) -> rownames(sppMatTemp.sw) #remove the sw from rownames
gsub(" SW", "", rownames(sppMatTemp.sw)) -> rownames(sppMatTemp.sw) #remove the sw from rownames
as.data.frame(sppMatTemp.sw) -> sppMatTemp.sw
names(sppMatTemp.sw)[which(names(sppMatTemp.sw) == "Symphyotrichum_novae-angliae")] <-
  "Symphyotrichum_novae.angliae"

###SAVE AS
file_name <- basename(orig_name)
gsub(".csv", "", file_name) -> file_name #dtop the .csv
gsub("^.*?\\.","", file_name) -> file_name
#get the year to add to a new column:
sub("^([^.]*.[^.]*).*", "\\1", file_name) -> date
gsub("\\..*","", file_name) -> year
sppCov.sw$year <- date 

new_name <- paste0("MEAN.sppCovMat.",file_name)
#outname <- paste(file_name, format(Sys.time(), c('%Y-%m-%d')), 'csv', sep = '.')
#write.csv(sppCov.sw2, file=paste0("../DATA/",year,"_VegetationCover/", new_name, ".csv"))
```
